In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [3]:
df['age_scaled'] = df['age']/100

In [4]:
df

age  affordibility  bought_insurance  age_scaled
0    22              1                 0        0.22
1    25              0                 0        0.25
2    47              1                 1        0.47
3    52              0                 0        0.52
4    46              1                 1        0.46
5    56              1                 1        0.56
6    55              0                 0        0.55
7    60              0                 1        0.60
8    62              1                 1        0.62
9    61              1                 1        0.61
10   18              1                 0        0.18
11   28              1                 0        0.28
12   27              0                 0        0.27
13   29              0                 0        0.29
14   49              1                 1        0.49
15   55              1                 1        0.55
16   25              0                 1        0.25
17   58              1                 1        0.58
18   19              0                 0        0.19
19   18              1                 0        0.18
20   21              1                 0        0.21
21   26              0                 0        0.26
22   40              1                 1        0.40
23   45              1                 1        0.45
24   50              1                 1        0.50
25   54              1                 1        0.54
26   23              1                 0        0.23
27   46              1                 0        0.46

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age_scaled','affordibility']],df.bought_insurance, test_size=0.2, random_state=42)

In [38]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
   
])
#optimizer = keras.optimizers.Adam(learning_rate=0.5)
model.compile(optimizer = 'adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - accuracy: 0.5000 - loss: 0.7428


/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.7424
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.7420
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.7416
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5000 - loss: 0.7411
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5000 - loss: 0.7407
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.7403
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5000 - loss: 0.7399
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5000 - loss: 0.7395
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5000 - loss: 0.7390
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5000 - loss: 0.7386
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5000 - loss: 0.7382
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5000 - l

In [39]:
y_pred = model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step


In [40]:
y_pred

array([[0.6733194 ],
       [0.66144764],
       [0.6749978 ],
       [0.45126277],
       [0.604739  ],
       [0.45315552]], dtype=float32)

In [41]:
coef, intercept = model.get_weights()

In [42]:
coef, intercept

(array([[0.76406646],
        [0.6513832 ]], dtype=float32),
 array([-0.3942271], dtype=float32))

In [16]:
def sigmoid(x):
    return 1/(1+np.exp(-x))


In [17]:

def log_loss2(y,y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i,1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y*np.log(y_pred)+(1-y)*np.log(1-y_pred))



In [31]:

def gradient_descent(x1,x2,y,epoch):
    w1 = w2 = 1
    b = 0
    rate = 0.5
    n = len(x1)
    for i in range(epoch):
        y_pred2 = w1*x1+w2*x2+b
        y_pred = sigmoid(y_pred2)
        loss = log_loss2(y,y_pred)
        
        w1d = (1/n)*np.dot(np.transpose(x1),(y_pred-y))
        w2d = (1/n)*np.dot(np.transpose(x2),(y_pred-y))
        bd =   np.mean(y_pred-y) 
        
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        b = b - rate * bd
        print(i,w1,w2,b,loss)
    return w1,w2,b



In [327]:
X_train['affordibility'].shape

(22,)

In [321]:
w1*X_train['age_scaled']+w2*X_train['affordibility']+b

17    1.58
22    1.40
11    1.28
13    0.29
15    1.55
1     0.25
4     1.46
5     1.56
2     1.47
16    0.25
23    1.45
3     0.52
26    1.23
24    1.50
18    0.19
27    1.46
20    1.21
7     0.60
10    1.18
14    1.49
19    1.18
6     0.55
dtype: float64

In [33]:
gradient_descent(X_train['age_scaled'],X_train['affordibility'],y_train,500)

0 0.9736899318847281 0.931388810977659 -0.11748951666770448 0.7428288579142563
1 0.9536535852311093 0.8740290167758512 -0.21881533456146035 0.7072146449948488
2 0.9393731039296968 0.8271852202997496 -0.3053620401943441 0.6814881914786812
3 0.930193258899806 0.7897792032048467 -0.37884372361582785 0.6633428084673968
4 0.9254091137248937 0.7605726653866934 -0.441082368200183 0.650742850709519
5 0.9243325693598606 0.738313053647322 -0.4938425798625155 0.6420508089402462
6 0.9263332963572349 0.7218280753843739 -0.5387319906498417 0.6360356979531206
7 0.9308580975636879 0.7100747303660235 -0.5771558825717441 0.631816485354411
8 0.9374354910317361 0.7021560855322683 -0.6103083840841516 0.6287844495353144
9 0.9456716791005844 0.6973185496313956 -0.639184616298235 0.626529442944178
10 0.9552423303850908 0.6949390905593646 -0.6646027475198829 0.624779988185889
11 0.9658829303208042 0.6945084189034805 -0.6872291753319572 0.6233586375123873
12 0.977379229173957 0.6956135754890374 -0.7076031311561

(6.0786647168303904, 1.2981890690045028, -3.2814399277519932)